### ISSUE TITLE
T19 when setting a dimm value the control will go back to 0

### ISSUE THREAD

**Issue by alvarolobato** [souliss/bindingopenhab2#16]
The slider value in a T19 dimmer is always 0. If you set a value it will change the brightness on the device accordingly but the slider will go back to 0 after a second or so.

Probably related to #10

**Comment by llamich** [comment]
I have the same problem with T19 and the last update of OH & souliss binding. I have OH 2.5.8-1 & org.openhab.binding.souliss-2.5.3-SNAPSHOT_202003231843.jar, binding doesn't update state of the slot.

**Comment by llamich** [comment]
Can you pass it to me compiled to test if it works for me? I am a newbie and I have not yet learned how to do it ... Thanks !!
